### ISSUE TITLE
20150715 Aグループ

### ISSUE THREAD

**Issue by aisaka** [ValLaboratory/dokushokai#145]
"鈴木隼人", "今井信夫", "石橋亮", "石橋かおる",

**Comment by n-imai** [comment]
人が多い！！

**Comment by chari270** [comment]
人が多い！！

**Comment by n-imai** [comment]
ユーザインターフェースとしてのWEB?
インターネットでなくてもHTMLを使用している。

**Comment by chari270** [comment]
ヘルプだったり、機器の設定画面だったり

**Comment by chari270** [comment]
WEB APIをwebサービスっていうのって一般的だったんだ

**Comment by chari270** [comment]
でも
＞が、この言葉はwebで提供するサービスやサイトを指すときにも使われます

やっぱりわかりにくいよね。駅すぱあとWebAPIのほうがいいよね

**Comment by chari270** [comment]
webで英単語を検索すると蜘蛛の巣より先にこっちの意味のが出てくるよ

**Comment by chari270** [comment]
URLとURIの違い
URIの方が広い
スパゲティとパスタてきな？

**Comment by n-imai** [comment]
HTTP1.1のメソッドと、HTML5の話
http://jxck.hatenablog.com/entry/why-form-dosent-support-put-delete

**Comment by chari270** [comment]
＞webはハイパーメディアの一例です
2例3例は？

昔あったようなCD-ROMコンテンツとか、ヘルプとか？

**Comment by chari270** [comment]
分散システムというとターミネーターのスカイネット

**Comment by kishibashi** [comment]
ハイパーメディア例
CD-ROM版の百科事典とか図鑑もだそうです
ありましたね〜
