### ISSUE TITLE
20150715 Cグループ

### ISSUE THREAD

**Issue by aisaka** [ValLaboratory/dokushokai#147]
"福本江梨奈", "鈴木省吾", "家田怜", "丸山ひかる",

**Comment by e-fkmt** [comment]
いえーい

**Comment by ssusan** [comment]
いえーい

**Comment by e-fkmt** [comment]
基幹システム#とは

**Comment by ieda** [comment]
いえーい

**Comment by e-fkmt** [comment]
## 基幹システム
企業の情報システムのうち、業務内容と直接に関わる販売や在庫管理、財務などを扱うもの。あるいは、単に、業務やサービスの中核となる重要なシステム。

**Comment by e-fkmt** [comment]
@hmaruyama さんが朗読しはじめた

**Comment by ieda** [comment]
プロジェクタの設定がリモコンでしかできなくて総務さん激おこ

**Comment by e-fkmt** [comment]
さっきまさにイラっとしてました

**Comment by e-fkmt** [comment]
@ssusan さん < 地デジ対応テレビの操作がつらい

**Comment by ssusan** [comment]
HTMLヘルプはこれのことか

https://ja.wikipedia.org/wiki/Microsoft_Compiled_HTML_Help

**Comment by e-fkmt** [comment]
話を広げようとするとこの後の範囲の話になっちゃう

**Comment by e-fkmt** [comment]
この辺の歴史は泥沼

**Comment by ieda** [comment]
XML 拡張可能構造化言語
XMLの一派生がHTMLというイメージ
構造の定義そのものをXMLは記述できる

**Comment by ssusan** [comment]
ハイパーメディアは技術というよりシステムの概念って感じなのかな？

**Comment by ssusan** [comment]
それを実現してるのがHTTPやHTMLやURIというか

**Comment by ssusan** [comment]
ハイパーメディアってもうちょっと名前なんとかならなかったのかな。
ハイパーだとなんかすごい感しか説明されてない気が。

**Comment by e-fkmt** [comment]
ハイパーリンク
テキストとか画像とか違うメディアのものをつなぎ合わせてるみたいな感覚でいいのでは。１つのメディアっぽくなってるみたいな。 by @ieda さん

**Comment by ssusan** [comment]
hyperには「〜を超えた」という意味もあるから、別々のメディアの境を超えたって意味合いなのかな？

**Comment by e-fkmt** [comment]
>Webはハイパーメディアの一例です

ということは他の例は？プレゼン作成ソフトとか？

**Comment by ieda** [comment]
世界初のハイパーメディアの1つとして Aspen Movie Map がある。ビル・アトキンソンの HyperCard はハイパーメディアを大衆化した。一方、ハイパーテキストを使った文学作品がリンクの将来性を見せつけた。
https://ja.wikipedia.org/wiki/%E3%83%8F%E3%82%A4%E3%83%91%E3%83%BC%E3%83%A1%E3%83%87%E3%82%A3%E3%82%A2

**Comment by e-fkmt** [comment]
> 多くの場合、ハイパーメディアは電子文書の形式であり、メディアプレーヤー、ウェブブラウザ、スタンドアロン型アプリケーションなどを使ってアクセスする。

メディアプレイヤーがハイパーメディアなのはなんでかな。動画（画像）と音声だから？
→非線形的に選択できるから？ by @ieda さん

**Comment by pupupopo88** [comment]
@ieda さんのメモ書き
![dokushokai](https://cloud.githubusercontent.com/assets/3654953/8740630/91ef348c-2c87-11e5-8f7a-54ebb9384e6e.jpg)

**Comment by ieda** [comment]
メディアに新聞を入れたのはちょっとミスでした。紙の方が良かった。
記録媒体としてのメディア、伝送・到達経路としてのメディア、再生機器としてのメディア、これらを包含したシステムとしてのメディア、は区別したほうが良さそうです。
