### ISSUE TITLE
20150715 Dグループ

### ISSUE THREAD

**Issue by aisaka** [ValLaboratory/dokushokai#148]
"北村素子", "大澤有美", "古谷朋香", "川本諭",

**Comment by t-furuya** [comment]
ハイパーメディアクリエイターってこれのことだったんだな

**Comment by t-furuya** [comment]
ユーザーインターフェースとしてのwebってwebサイトみたいなものじゃないのか

**Comment by t-furuya** [comment]
JSONによみがながふってある

**Comment by t-furuya** [comment]
JSONって馴染みないのかな？

**Comment by t-furuya** [comment]
URLとURIの違いとは

**Comment by t-furuya** [comment]
ハイパーリンクのハイパーってなんですか？

**Comment by t-furuya** [comment]
ハイパーについて
https://ja.wikipedia.org/wiki/%E3%83%8F%E3%82%A4%E3%83%91%E3%83%BC

**Comment by o-sawa** [comment]
ハイパーリンクのハイパー #とは が調べても出てこなかった
すごいリンクってこと？

**Comment by t-furuya** [comment]
とりあえずハイパーつけとけ的なことなのかな？

**Comment by t-furuya** [comment]
（ハイパーがゲシュタルト崩壊してきた）

**Comment by o-sawa** [comment]
ハイパーテキストを結びつけるリンクだからハイパーリンク
https://ja.m.wikipedia.org/wiki/ハイパーテキスト

**Comment by t-furuya** [comment]
HTMLやCSSのはなしは無いのかな？
→ちょこちょこ出てくるっぽい（メインではない）

**Comment by t-furuya** [comment]
絶対分散システムしろってことなのかな
→サーバーが1ここわれたらweb使えませんとかじゃ誰もweb使いませんよね

**Comment by t-furuya** [comment]
次回は2-3まで

**Comment by t-furuya** [comment]
次回：7/29

**Comment by t-furuya** [comment]
次回ファシリ：そえだ

**Comment by o-sawa** [comment]
次回範囲: 2-3まで
日付: 7/29
ファシリ: @soe-j 

来週はコーディングを支える技術
