### ISSUE TITLE
20150715 Eグループ

### ISSUE THREAD

**Issue by aisaka** [ValLaboratory/dokushokai#149]
"廣戸晶", "河津弘亮", "添田悠央", "青山正太郎", "藤掛優希"

**Comment by soe-j** [comment]
一項目ごとに見ていきますか―

**Comment by soe-j** [comment]
ブラウザってターミナル入る？

**Comment by soe-j** [comment]
webは略語じゃない(たぶん)

**Comment by soe-j** [comment]
蜘蛛の巣的な意味

**Comment by hirotyobi-val** [comment]
>　乗り換え情報を調べたり
>　乗り換え情報を調べたり
>　乗り換え情報を調べたり

**Comment by soe-j** [comment]
ルータの設定ブラウザでやるなあ

**Comment by soe-j** [comment]
テレビの設定....?

**Comment by soe-j** [comment]
ビデオとかプリンタがサーバになって、設定画面をhtmlとかで提供している、という体型がよく使われる

**Comment by hirotyobi-val** [comment]
あとカラオケのデンモクとか

**Comment by soe-j** [comment]
ハブもターミナル使うよりかはブラウザだよねぇ

**Comment by soe-j** [comment]
webって言ってる範囲が思ったより広い

**Comment by soe-j** [comment]
スマホで録画予約とかできる仕組み
中身全部webで統一されているが故に、ハッキングされたときに全部穴があいちゃう

**Comment by soe-j** [comment]
その昔CGIとか、APIとして使うのに?とか#とかついててパラメータ渡すタイプもAPIといえるのか

**Comment by soe-j** [comment]
一応言えるのでは....
良いAPIのURLかどうかというと......わ、るい

この後この本でRESTfulについて詳しくやります

**Comment by soe-j** [comment]
ビデオとかプリンタとかのapatchのせたらできすぎるから軽量版の何かがのってるのだろう

**Comment by soe-j** [comment]
URIってURLと何がちがうねん

**Comment by soe-j** [comment]
52ページを御覧ください

**Comment by soe-j** [comment]
URNとURLとあって、それを総称してURI

**Comment by soe-j** [comment]
URNがリソースの名前
URLがリソースがある場所

**Comment by soe-j** [comment]
URNはAWSのインスタンスとか表すのに使われている

**Comment by soe-j** [comment]
置いてある場所が変わっても、識別できるようにつけてあるのがURN

**Comment by soe-j** [comment]
microformats　#とは

**Comment by soe-j** [comment]
HTML（またはXHTML）ウェブページにおける、意味を表現するための小さなマークアップである。

**Comment by soe-j** [comment]
はーなるほどわからん

**Comment by soe-j** [comment]
htmlタグ内にあるclassとかrelとかrevとか

**Comment by soe-j** [comment]
あー

**Comment by hkawazu** [comment]
ハイパーメディアと聞くと　エリカ様の元？旦那を思い浮かべてしまう。
